#!/usr/bin/env bundle exec ruby
require "bundler/setup"

require "nokogiri"
require "colorize"

SCHEMA_FILE = "schema.xsd"

def validate(folder, xsd_file, xml_file)
  Dir.chdir(folder) do
    errors = []
    begin
      xsd = Nokogiri::XML::Schema(File.read(xsd_file))
      errors.push(*xsd.errors) if xsd.errors.any?
    rescue Nokogiri::XML::SyntaxError => e
      errors << e.message
    end

    begin
      doc = Nokogiri::XML(File.read(xml_file))
      errors.push(*doc.errors) if doc.errors.any?
    rescue Nokogiri::XML::SyntaxError => e
      errors << e.message
    end

    begin
      xsd.validate(doc).each do |error|
        errors << error.message
      end
    rescue NoMethodError
      # no need to log this one
    end
    errors
  end
end

total_files = 0
valid_files = 0
skipped_files = 0
invalid_files = 0

# for all directories
Dir.glob("**/*/") do |folder|
  puts "Going through #{folder}"
  # if there are multiple schemas
  xsd_files = Dir[File.join(folder, "*.xsd")]
  if xsd_files.length > 1
    total_files += xsd_files.length
    invalid_files += xsd_files.length
    files_list = xsd_files.map { |f| File.basename(f) }.join(", ")
    puts "   Multiple schema files detected (#{files_list}) - marking them as invalid!".colorize(:red)
    puts "   You should have only one schema file in a directory called: #{SCHEMA_FILE}".colorize(:red)
    next
  end
  xsd_file = "#{folder}#{SCHEMA_FILE}"
  # for all xml files in that directory
  xml_files = Dir.glob("#{folder}*.xml")
  if File.exists? xsd_file
    # if there are no XML files to validate against the schema
    if xml_files.empty?
      total_files += 1
      skipped_files += 1
      puts "   Skipping #{xsd_file} - could not find any XML files to validate against".colorize(:yellow)
      next
    end
    xml_files.each do |xml_file|
      total_files += 1
      print "   Validating #{xml_file} against #{xsd_file} ... ".colorize(:cyan)
      errors = validate(folder, File.basename(xsd_file), File.basename(xml_file))
      if errors.empty?
        valid_files += 1
        puts "valid!".colorize(:green)
      else
        invalid_files += 1
        puts "invalid!".colorize(:red)
        errors.each do |msg|
          puts "      #{msg}".colorize(:red)
        end
      end
    end
  else
    if !xml_files.empty?
      total_files += xml_files.length
      invalid_files += xml_files.length
      files_list = xml_files.map { |f| File.basename(f) }.join(", ")
      puts "   Found XML files without any schema definition (#{files_list}) - marking them as invalid!".colorize(:red)
      puts "   You should either remove them or create a schema definition file (#{SCHEMA_FILE})".colorize(:red)
    end
  end
end

info = "\n#{total_files} files ("
info << "#{invalid_files} invalid".colorize(:red) << ", " if invalid_files > 0
info << "#{skipped_files} skipped".colorize(:yellow) << ", " if skipped_files > 0
info << "#{valid_files} valid".colorize(:green) << ")"
puts info
